server:
  port: 8080

ribbon:
  ConnectTimeout: 120000
  ReadTimeout: 120000

---
spring:
  profiles: local
  cloud:
    config:
      uri: http://localhost:8888
      label: develop

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: real
  cloud:
    config:
      uri: http://localhost:8888
      label: develop

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
