server:
  port: ${PORT:8810}

---
spring:
  profiles: local
  cloud:
    config:
      uri: http://localhost:8888
      label: develop

name: local-yml
environment: local

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

servers: 
    - local.abc.com
    - local.xyz.com
 
---
spring:
  profiles: real
  cloud:
    config:
      uri: http://localhost:8888
      label: develop
name: real-yml
environment: real

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

servers: 
    - www.abc.com
    - www.xyz.com