server:
  port: 8810

spring:
  profiles: local
  cloud:
    config:
      uri: http://localhost:8888
      label: develop
name: local-YAML
environment: local
servers: 
    - local.abc.com
    - local.xyz.com
 
---
spring:
  profiles: prod
  cloud:
    config:
      uri: http://localhost:8888
      label: develop
spring:
    profiles: prod
name: prod-YAML
environment: production
servers: 
    - www.abc.com
    - www.xyz.com