server:
  port: 8810
  profiles:
    active: local

---
spring:
  profiles: local
  cloud:
    config:
      uri: http://localhost:8888
      label: develop
name: local-YAML
environment: local
servers: 
    - local.abc.com
    - local.xyz.com
 
---
spring:
  profiles: real
  cloud:
    config:
      uri: http://localhost:8888
      label: develop
spring:
    profiles: real
name: real-YAML
environment: real
servers: 
    - www.abc.com
    - www.xyz.com